name: pypeit
channels:
  - conda-forge
dependencies:
  - python>=3.11,<3.15
  - numpy
  - astropy
  - scipy
  - matplotlib
  - scikit-learn
  - ipython
  - pyside6
  - llvm-openmp
  - pip
  - pip:
    - pypeit
    - specutils>=2.0
