#!/bin/bash

cd doc
printf "\n\nUpdating API documentation and testing html compilation\n\n"
sleep 1
make clean ; make html
git add api
git add pypeit_par.rst
cd ../

printf "Check the modified files with:\n\n    git status\n\nFix any errors/warnings in:\n\n    doc/sphinx_warnings.out\n\nAdd any additional changes with:\n\n    git add -u\n\nAnd commit the changes with: \n\n   git commit -m 'updated docs'\n\n"

exit 0

