#!/bin/bash

cd doc
make clean ; make apirst
cd ../
git add doc/api
git add doc/pypeit_par.rst

printf "Now check the modified files with:\n\n    git status\n\nAnd commit the changes with: \n\n   git commit -m 'updated docs'\n\n"

exit 0

