"""
Module to test object finding in pypeit.core.findobj_skymask.
"""
import numpy as np

from pypeit.core import findobj_skymask


def synthetic_echelle(nspec=100, nspat=64, norders=3, width=8.0,
                      counts=1000.0):
    """
    Build a synthetic echelle frame with slit-filling flux in each order.

    Each order is a vertical stripe of constant flux (the 'star' fills
    the slit), separated by dark inter-order gaps.

    Args:
        nspec (:obj:`int`, optional):
            Number of spectral pixels.
        nspat (:obj:`int`, optional):
            Number of spatial pixels.
        norders (:obj:`int`, optional):
            Number of orders.
        width (:obj:`float`, optional):
            Order width in pixels.
        counts (:obj:`float`, optional):
            Flux level within each order.

    Returns:
        tuple: image, ivar, slitmask, slit_left, slit_righ,
        slit_spat_id, order_vec
    """
    image = np.zeros((nspec, nspat), dtype=float)
    slitmask = np.full((nspec, nspat), -1, dtype=int)
    slit_left = np.zeros((nspec, norders), dtype=float)
    slit_righ = np.zeros((nspec, norders), dtype=float)
    slit_spat_id = np.zeros(norders, dtype=int)
    gap = (nspat - norders*width)/(norders + 1)
    for iord in range(norders):
        left = gap + iord*(width + gap)
        righ = left + width
        slit_left[:, iord] = left
        slit_righ[:, iord] = righ
        spat_id = int(np.rint(0.5*(left + righ)))
        slit_spat_id[iord] = spat_id
        icols = (np.arange(nspat) >= left) & (np.arange(nspat) < righ)
        image[:, icols] = counts
        slitmask[:, icols] = spat_id
    ivar = np.full_like(image, 1.0/np.fmax(counts, 1.0))
    # Descending physical echelle order numbers
    order_vec = np.arange(norders)[::-1] + 60
    return image, ivar, slitmask, slit_left, slit_righ, slit_spat_id, \
        order_vec


def test_ech_slit_center_objs():
    """
    Check that forced slit-center object creation returns one object per
    order at the order center, with slit-width apertures and a positive
    S/N for a bright slit-filling source.

    Generated by JXP and Claude.
    """
    image, ivar, slitmask, slit_left, slit_righ, slit_spat_id, order_vec \
        = synthetic_echelle()
    norders = order_vec.size

    sobjs = findobj_skymask.ech_slit_center_objs(
        image, ivar, slitmask, slit_left, slit_righ, slit_spat_id,
        order_vec, det='DET01',
        specobj_dict={'SLITID': 999, 'DET': 'DET01',
                      'OBJTYPE': 'science', 'PYPELINE': 'Echelle'})

    # One object per order, all the same (single) object
    assert len(sobjs) == norders, \
        'Should force exactly one object per echelle order'
    assert np.all(sobjs.ECH_OBJID == 1), \
        'All forced objects should share ECH_OBJID = 1 (a single object)'
    assert np.all(sobjs.OBJID == 1), \
        'All forced objects should share OBJID = 1 (a single object)'
    assert np.array_equal(sobjs.ECH_ORDER, order_vec), \
        'Objects should carry the echelle order numbers of their orders'
    assert np.array_equal(sobjs.SLITID, slit_spat_id), \
        'Objects should carry the spat_id of their orders'

    # Traces at the order centers, apertures spanning the slit
    for iord, sobj in enumerate(sobjs):
        center = 0.5*(slit_left[:, iord] + slit_righ[:, iord])
        assert np.allclose(sobj.TRACE_SPAT, center), \
            'Trace should be forced to the order center (edge midpoint)'
        assert sobj.SPAT_FRACPOS == 0.5, \
            'Forced object should sit at the fractional order center'
        assert np.isclose(sobj.FWHM, 8.0), \
            'FWHM should equal the median order width (8 pixels here)'
        assert np.isclose(sobj.BOX_R_PIX, 4.0), \
            'Boxcar radius should be half the order width, spanning the order'
        # Bright slit-filling source must register a positive S/N
        assert sobj.ech_snr > 0., \
            'Bright slit-filling source should register a positive S/N'
        assert sobj.NAME is not None, \
            'The SpecObj name should be set for downstream IO'
