"""
Tests for the PypeIt Dashboard (Stage 0 — walking skeleton).

These replace the earlier tests that targeted the reference prototype
(``pypeit.dashboard.dashboard``), which has been moved to
``pypeit/dashboard/prototype/`` and is not carried forward.

They are split into:

* Headless tests of the Qt-free model layer (``read_header_info``,
  ``HeaderInfo``), which run with plain ``pytest`` and need no display.
* Structural widget tests of the views, which use ``pytest-qt`` with the
  offscreen Qt platform (mirroring the ``setup_gui`` test approach).  They
  assert the *structure* of the window (the tab bar, the header fields),
  not its pixel-level appearance.

All are CI-safe: they require no RAW_DATA and use a minimal bundled
``.pypeit`` fixture.

Generated by JXP and Claude.
"""

import os
# Ensure Qt can initialize without a display before any Qt import.
os.environ.setdefault('QT_QPA_PLATFORM', 'offscreen')

from pathlib import Path

import pytest

# qtpy/pyqt6 are dependencies, but skip cleanly if the GUI stack is absent.
pytest.importorskip('qtpy')

from pypeit.dashboard.model import read_header_info, HeaderInfo, \
    PYPELINE_DISPLAY


def data_path(filename):
    """
    Return the path to a file in the test ``files`` directory.

    Generated by JXP and Claude.

    Args:
        filename (:obj:`str`): The file basename.

    Returns:
        str: The absolute path to the test file.
    """
    return str(Path(__file__).parent / 'files' / filename)


# -----------------------------------------------------------------------
# Headless model-layer tests (no Qt, no display)
# -----------------------------------------------------------------------

def test_read_header_info_fields():
    """
    The header metadata is parsed correctly from a minimal ``.pypeit``
    file (R6 fields).  Generated by JXP and Claude.
    """
    pyfile = data_path('dashboard_shane_kast_blue.pypeit')
    info = read_header_info(pyfile)
    assert isinstance(info, HeaderInfo)
    assert info.pypeit_file == 'dashboard_shane_kast_blue.pypeit'
    assert info.spectrograph == 'shane_kast_blue'
    assert info.setup == 'A'
    # shane_kast_blue is a long-slit (MultiSlit) spectrograph.
    assert info.path == 'MultiSlit'
    # redux_dir defaults to the directory containing the .pypeit file.
    assert info.redux_dir == str(Path(pyfile).parent.resolve())


def test_read_header_info_redux_path_override(tmp_path):
    """
    An explicit ``redux_path`` overrides the default directory.
    Generated by JXP and Claude.
    """
    pyfile = data_path('dashboard_shane_kast_blue.pypeit')
    info = read_header_info(pyfile, redux_path=str(tmp_path))
    assert info.redux_dir == str(tmp_path.resolve())


def test_read_header_info_missing_file():
    """
    A named-but-absent ``.pypeit`` file raises a clear error (R11 edge
    case).  Generated by JXP and Claude.
    """
    with pytest.raises(FileNotFoundError):
        read_header_info('/no/such/file.pypeit')


def test_pypeline_display_maps_ifu():
    """
    The internal 'SlicerIFU' pypeline is displayed as 'IFU' (S0-Q7).
    Generated by JXP and Claude.
    """
    assert PYPELINE_DISPLAY['SlicerIFU'] == 'IFU'
    assert PYPELINE_DISPLAY['MultiSlit'] == 'MultiSlit'
    assert PYPELINE_DISPLAY['Echelle'] == 'Echelle'


# -----------------------------------------------------------------------
# Structural widget tests (pytest-qt, offscreen)
# -----------------------------------------------------------------------

def _example_header_info():
    """
    Build a representative :class:`HeaderInfo` for the widget tests.

    Generated by JXP and Claude.

    Returns:
        :class:`HeaderInfo`: Example header metadata.
    """
    return read_header_info(data_path('dashboard_shane_kast_blue.pypeit'))


def _example_model():
    """
    Build a `DashboardModel` from the minimal ``.pypeit`` fixture (no state
    file → "not started"), for the Stage 0 window/header tests.

    Generated by JXP and Claude.

    Returns:
        :class:`~pypeit.dashboard.model.DashboardModel`: The example model.
    """
    return dash_model.DashboardModel(
        data_path('dashboard_shane_kast_blue.pypeit'), derive=False)


def test_main_window_tab_bar(qtbot):
    """
    The main window has exactly the Status | Calibrations tab bar (R3/C1),
    in that order.  Generated by JXP and Claude.
    """
    from pypeit.dashboard.view.main_window import (DashboardMainWindow,
                                                   TAB_LABELS)
    window = DashboardMainWindow(_example_model())
    qtbot.addWidget(window)
    tabs = [window.tab_widget.tabText(i)
            for i in range(window.tab_widget.count())]
    assert tabs == list(TAB_LABELS)
    assert tabs == ['Status', 'Calibrations']


def test_header_banner_fields(qtbot):
    """
    The header banner exposes all five R6 fields, populated from the
    metadata.  Generated by JXP and Claude.
    """
    from pypeit.dashboard.view.main_window import DashboardMainWindow
    window = DashboardMainWindow(_example_model())
    qtbot.addWidget(window)
    labels = window.header.value_labels
    assert set(labels.keys()) == {'pypeit_file', 'spectrograph', 'setup',
                                  'path', 'redux_dir'}
    assert labels['spectrograph'].text() == 'shane_kast_blue'
    assert labels['setup'].text() == 'A'
    assert labels['path'].text() == 'MultiSlit'


def test_main_window_title_and_render(qtbot, tmp_path):
    """
    The window has the expected title and renders offscreen without error
    (a basic smoke test of the walking skeleton).  Generated by JXP and
    Claude.
    """
    from pypeit.dashboard.view.main_window import DashboardMainWindow
    window = DashboardMainWindow(_example_model())
    qtbot.addWidget(window)
    window.resize(1650, 900)
    assert window.windowTitle() == 'PypeIt Dashboard'
    # grab() exercises the full paint path; saving proves it produced pixels.
    out = tmp_path / 'render.png'
    assert window.grab().save(str(out))
    assert out.is_file() and out.stat().st_size > 0


# -----------------------------------------------------------------------
# Stage 1: headless state-data-layer tests (DashboardModel, no Qt/RAW_DATA)
# -----------------------------------------------------------------------

from pypeit.dashboard import model as dash_model
from pypeit.dashboard import palette


def _make_redux(tmp_path, case):
    """
    Stage a reduction directory: the minimal ``.pypeit`` fixture as
    ``shane_kast_blue_A.pypeit`` plus, when ``case`` is given, the matching
    state fixture as ``shane_kast_blue_A_state.json`` (the name the model
    derives).  Returns the ``.pypeit`` path.

    Generated by JXP and Claude.

    Args:
        tmp_path (`pathlib.Path`_): Pytest temporary directory.
        case (:obj:`str`, optional): Fixture case name (e.g. ``healthy``),
            or ``None`` to stage no state file.

    Returns:
        str: Path to the staged ``.pypeit`` file.
    """
    pf = tmp_path / 'shane_kast_blue_A.pypeit'
    pf.write_text(
        Path(data_path('dashboard_shane_kast_blue.pypeit')).read_text())
    if case is not None:
        sj = tmp_path / 'shane_kast_blue_A_state.json'
        sj.write_text(
            Path(data_path(f'dashboard_state_{case}.json')).read_text())
    return str(pf)


def test_model_load_healthy(tmp_path):
    """
    A healthy state loads from the state file and normalizes correctly.
    Generated by JXP and Claude.
    """
    m = dash_model.DashboardModel(_make_redux(tmp_path, 'healthy'),
                                  derive=False)
    assert m.load_status == dash_model.LOAD_STATE_FILE
    assert m.is_started()
    table = m.status_table()
    assert list(table.columns) == dash_model.STATUS_COLUMNS
    # A successful, required, in-pipeline step.
    wv = table[table['step'] == 'wv_calib'].iloc[0]
    assert wv['status'] == 'success'
    assert bool(wv['required']) is True    # normalized to a real bool
    assert bool(wv['in_pipeline']) is True
    assert wv['output_file'] == 'WaveCalib_A_0_DET01.fits'
    # 'align' is not in the MultiSlit pipeline -> in_pipeline False, absent.
    align = table[table['step'] == 'align'].iloc[0]
    assert not bool(align['in_pipeline'])
    assert align['status'] == 'absent'
    assert align['required'] is None
    # 'bpm' is never tracked in the state, so it is not a row.
    assert 'bpm' not in set(table['step'])


def test_model_step_order_path_aware(tmp_path):
    """
    The step order matches the MultiSlit pipeline and omits ``bpm`` by
    default.  Generated by JXP and Claude.
    """
    m = dash_model.DashboardModel(_make_redux(tmp_path, 'healthy'),
                                  derive=False)
    order = m.step_order()
    assert order == ['bias', 'dark', 'slits', 'arc', 'tiltimg', 'wv_calib',
                     'tilts', 'scattlight', 'flats']
    assert 'bpm' not in order
    assert 'bpm' in m.step_order(include_bpm=True)


def test_model_calib_det_pairs(tmp_path):
    """
    The (calib_id, det) enumeration returns the single kast pair, det raw.
    Generated by JXP and Claude.
    """
    m = dash_model.DashboardModel(_make_redux(tmp_path, 'healthy'),
                                  derive=False)
    assert m.calib_det_pairs() == [(0, 1)]


def test_model_failed_step(tmp_path):
    """
    A failed step is normalized as ``status == 'fail'``.  Generated by JXP
    and Claude.
    """
    m = dash_model.DashboardModel(_make_redux(tmp_path, 'failed'),
                                  derive=False)
    wv = m.status_table()
    row = wv[wv['step'] == 'wv_calib'].iloc[0]
    assert row['status'] == 'fail'


def test_model_not_started_with_empty_state(tmp_path):
    """
    A state file with no calibration entries reads as "not started"
    (loaded, but empty).  Generated by JXP and Claude.
    """
    m = dash_model.DashboardModel(_make_redux(tmp_path, 'not_started'),
                                  derive=False)
    assert m.load_status == dash_model.LOAD_STATE_FILE
    assert not m.is_started()
    assert m.status_table().empty
    assert m.calib_det_pairs() == []


def test_model_not_started_no_state_file(tmp_path):
    """
    No state file and deriving disabled -> ``not_started`` (R11), no crash.
    Generated by JXP and Claude.
    """
    m = dash_model.DashboardModel(_make_redux(tmp_path, None), derive=False)
    assert m.load_status == dash_model.LOAD_NOT_STARTED
    assert not m.is_started()
    assert m.status_table().empty


def test_model_malformed_state(tmp_path):
    """
    A malformed state file is reported as ``malformed`` without raising
    (R11).  Generated by JXP and Claude.
    """
    m = dash_model.DashboardModel(_make_redux(tmp_path, 'malformed'),
                                  derive=False)
    assert m.load_status == dash_model.LOAD_MALFORMED
    assert m.run_state is None
    assert m.status_table().empty


def test_model_file_not_found(tmp_path):
    """
    A missing ``.pypeit`` file is reported, not raised (R11).  Generated by
    JXP and Claude.
    """
    m = dash_model.DashboardModel(str(tmp_path / 'nope.pypeit'),
                                  derive=False)
    assert m.load_status == dash_model.LOAD_FILE_NOT_FOUND
    assert m.header_info is None
    assert m.status_table().empty


# --- palette (Dashboard-wide status palette) ---------------------------

def test_palette_categories():
    """
    ``classify`` maps (required, status, in_pipeline) to the design's
    palette categories.  Generated by JXP and Claude.
    """
    assert palette.classify(True, 'success', True) == palette.SUCCESS
    assert palette.classify(True, 'complete', True) == palette.SUCCESS
    assert palette.classify(True, 'running', True) == palette.RUNNING
    assert palette.classify(True, 'fail', True) == palette.FAIL
    assert palette.classify(True, 'undone', True) == palette.REQUIRED_UNDONE
    assert palette.classify(False, 'undone', True) == palette.OPTIONAL
    # Not in the spectrograph's pipeline -> dimmed, regardless of status.
    assert palette.classify(True, 'success', False) == palette.NOT_USED


def test_palette_colors_and_glyphs_match_design():
    """
    The light palette hex + glyph match the design doc table exactly.
    Generated by JXP and Claude.
    """
    expected = {
        (True, 'success', True): ('#2E7D32', '✓'),
        (True, 'running', True): ('#EF6C00', '⏳'),
        (True, 'fail', True): ('#C62828', '✗'),
        (True, 'undone', True): ('#FFFFFF', '○'),
        (False, 'undone', True): ('#9E9E9E', '–'),
        (True, 'success', False): ('#BDBDBD', '–'),
    }
    for (req, status, in_pipe), (hexcol, glyph) in expected.items():
        style = palette.step_style(req, status, in_pipe, theme='light')
        assert style.color == hexcol
        assert style.glyph == glyph
    # Dark theme returns the dark hex set (different fills, same glyph).
    dark = palette.step_style(True, 'success', True, theme='dark')
    assert dark.color == palette.DARK_COLORS[palette.SUCCESS]
    assert dark.glyph == '✓'


def test_palette_worst_category():
    """
    ``worst_category`` picks the most severe category; optional/not-used
    never worsen an otherwise-successful cell (R17).  Generated by JXP and
    Claude.
    """
    assert palette.worst_category(
        [palette.SUCCESS, palette.FAIL]) == palette.FAIL
    assert palette.worst_category(
        [palette.SUCCESS, palette.RUNNING]) == palette.RUNNING
    assert palette.worst_category(
        [palette.SUCCESS, palette.REQUIRED_UNDONE]) \
        == palette.REQUIRED_UNDONE
    # optional / not_used do not worsen a successful cell.
    assert palette.worst_category(
        [palette.SUCCESS, palette.OPTIONAL, palette.NOT_USED]) \
        == palette.SUCCESS
    assert palette.worst_category([]) == palette.NOT_USED


# -----------------------------------------------------------------------
# Stage 2: Status view (pytest-qt, offscreen) — structural tests
# -----------------------------------------------------------------------

def _status_view(case, tmp_path, qtbot):
    """
    Build a `StatusView` over a staged fixture reduction.

    Generated by JXP and Claude.

    Args:
        case (:obj:`str`): Fixture case (e.g. ``healthy``), or ``None``.
        tmp_path (`pathlib.Path`_): Pytest temp dir.
        qtbot: pytest-qt fixture.

    Returns:
        tuple: ``(StatusView, DashboardModel)``.
    """
    from pypeit.dashboard.view.status_view import StatusView
    model = dash_model.DashboardModel(_make_redux(tmp_path, case),
                                      derive=False)
    view = StatusView(model)
    qtbot.addWidget(view)
    return view, model


def test_status_view_healthy_table(tmp_path, qtbot):
    """
    The healthy Status view shows the scoped table (Step | Required |
    Status | Output) with one row per pipeline step.  Generated by JXP and
    Claude.
    """
    view, model = _status_view('healthy', tmp_path, qtbot)
    table = view._table
    assert table is not None
    headers = [table.horizontalHeaderItem(c).text()
               for c in range(table.columnCount())]
    assert headers == ['Step', 'Required', 'Status', 'Output']
    assert table.rowCount() == len(model.step_order())
    # The wv_calib row reads as a success (✓).
    steps = [table.item(r, 0).text() for r in range(table.rowCount())]
    wv = steps.index('wv_calib')
    assert '✓' in table.item(wv, 2).text()
    assert table.item(wv, 3).text() == 'WaveCalib_A_0_DET01.fits'


def test_status_view_scope_dropdowns(tmp_path, qtbot):
    """
    The scope drop-downs are populated from the model's (calib, det) pairs.
    Generated by JXP and Claude.
    """
    view, model = _status_view('healthy', tmp_path, qtbot)
    assert view._group_combo.count() == 1
    assert view._group_combo.itemData(0) == 0
    assert view._det_combo.count() == 1
    # det is formatted readably by the view (DET01 for a single detector).
    assert view._det_combo.itemText(0) == 'DET01'


def test_status_view_failed_row(tmp_path, qtbot):
    """
    A failed step renders with the fail glyph (✗).  Generated by JXP and
    Claude.
    """
    view, _ = _status_view('failed', tmp_path, qtbot)
    table = view._table
    steps = [table.item(r, 0).text() for r in range(table.rowCount())]
    wv = steps.index('wv_calib')
    assert '✗' in table.item(wv, 2).text()


def test_status_view_not_started_message(tmp_path, qtbot):
    """
    A not-started (empty) state renders an edge message and no table (R11).
    Generated by JXP and Claude.
    """
    view, _ = _status_view('not_started', tmp_path, qtbot)
    assert view._table is None


def test_status_view_malformed_message(tmp_path, qtbot):
    """
    A malformed state renders an edge message and no table (R11).
    Generated by JXP and Claude.
    """
    view, model = _status_view('malformed', tmp_path, qtbot)
    assert model.load_status == dash_model.LOAD_MALFORMED
    assert view._table is None


# -----------------------------------------------------------------------
# Stage 3: model detail accessors, palette skip, inspect builders
# -----------------------------------------------------------------------

def _multidet_model(tmp_path):
    """
    A `DashboardModel` over the multi-slit/multi-detector fixture.

    Generated by JXP and Claude.
    """
    return dash_model.DashboardModel(_make_redux(tmp_path, 'multidet'),
                                     derive=False)


def test_model_step_metrics(tmp_path):
    """
    step_metrics returns entry-level metrics per step (Stage 3).  Generated
    by JXP and Claude.
    """
    m = _multidet_model(tmp_path)
    assert m.step_metrics('bias', 0, 1)['mean'] == 1001.0
    assert m.step_metrics('slits', 0, 1)['nslits'] == 3
    fm = m.step_metrics('flats', 0, 1)
    assert fm['corrections'] == ['pixelflat', 'spat_illum']
    assert fm['pixelflat_source'] == 'raw'


def test_model_slit_table(tmp_path):
    """
    slit_table returns per-slit rows; flats carries per-correction metrics
    and a `skip` slit (Stage 3).  Generated by JXP and Claude.
    """
    m = _multidet_model(tmp_path)
    wv = m.slit_table('wv_calib', 0, 1)
    assert len(wv) == 3
    assert 'rms' in wv[0] and wv[0]['status'] == 'success'
    flats = m.slit_table('flats', 0, 1)
    assert [r['status'] for r in flats] == ['success', 'success', 'skip']
    assert set(flats[0]['corrections']) == {'pixelflat', 'spat_illum'}
    # Steps without per-slit data return an empty list.
    assert m.slit_table('bias', 0, 1) == []


def test_model_output_and_calib_paths(tmp_path):
    """
    output_path joins Calibrations/<output_file>; calib_file_path builds a
    file by naming convention (Edges for slits).  Generated by JXP and
    Claude.
    """
    m = _multidet_model(tmp_path)
    out = m.output_path('wv_calib', 0, 1)
    assert out.name == 'WaveCalib_A_0_DET01.fits'
    assert out.parent.name == 'Calibrations'
    edges = m.calib_file_path('Edges', 0, 1, ext='fits.gz')
    assert edges.name == 'Edges_A_0_DET01.fits.gz'


def test_palette_slit_style_skip():
    """
    The per-slit palette maps `skip` to a distinct category with its glyph
    (S3-Q15).  Generated by JXP and Claude.
    """
    assert palette.slit_style('skip').category == palette.SKIP
    assert palette.slit_style('skip').glyph == '⊘'
    assert palette.slit_style('success').category == palette.SUCCESS
    assert palette.slit_style('fail').category == palette.FAIL
    assert palette.SKIP in palette.LIGHT_COLORS
    assert palette.SKIP in palette.DARK_COLORS


def test_inspect_output_commands(tmp_path):
    """
    inspect.output_command builds the right argv per step, incl. the
    non-uniform cases (S3-Q12/Q13).  Generated by JXP and Claude.
    """
    from pypeit.dashboard import inspect as dash_inspect
    m = _multidet_model(tmp_path)
    # Processed image → pypeit_view_fits --proc (S3-Q13).
    bias = dash_inspect.output_command(m, 'bias', 0, 1)
    assert bias[0] == 'pypeit_view_fits' and bias[1] == 'shane_kast_blue'
    assert bias[-1] == '--proc' and bias[2].endswith('Bias_A_0_DET01.fits')
    # slits → pypeit_chk_edges on the Edges file, not the Slits output.
    slits = dash_inspect.output_command(m, 'slits', 0, 1)
    assert slits[0] == 'pypeit_chk_edges'
    assert slits[1].endswith('Edges_A_0_DET01.fits.gz')
    # wv_calib → pypeit_chk_wavecalib on its output.
    wv = dash_inspect.output_command(m, 'wv_calib', 0, 1)
    assert wv[0] == 'pypeit_chk_wavecalib'
    assert wv[1].endswith('WaveCalib_A_0_DET01.fits')
    # An input frame → pypeit_view_fits <spec> <file>.
    vin = dash_inspect.view_input_command(m, 'b3.fits.gz')
    assert vin == ['pypeit_view_fits', 'shane_kast_blue', 'b3.fits.gz']


# -----------------------------------------------------------------------
# Stage 3: Calibrations view (pytest-qt, offscreen) — structural tests
# -----------------------------------------------------------------------

def _calib_view(case, tmp_path, qtbot):
    """
    Build a `CalibrationsView` over a staged fixture reduction.

    Generated by JXP and Claude.
    """
    from pypeit.dashboard.view.calibrations_view import CalibrationsView
    model = dash_model.DashboardModel(_make_redux(tmp_path, case),
                                      derive=False)
    view = CalibrationsView(model)
    qtbot.addWidget(view)
    return view, model


def test_calib_view_button_row_path_aware(tmp_path, qtbot):
    """
    The step-button row contains the spectrograph's steps in order, with
    `bpm` omitted (C3/C12/C13).  Generated by JXP and Claude.
    """
    view, model = _calib_view('multidet', tmp_path, qtbot)
    assert list(view._step_buttons.keys()) == model.step_order()
    assert 'bpm' not in view._step_buttons


def test_calib_view_detector_selector_multidet(tmp_path, qtbot):
    """
    The detector selector lists both detectors (C2, multi-detector).
    Generated by JXP and Claude.
    """
    view, _ = _calib_view('multidet', tmp_path, qtbot)
    assert view._group_combo.count() == 1
    assert view._det_combo.count() == 2


def test_calib_view_per_slit_table(tmp_path, qtbot):
    """
    Selecting `wv_calib` shows a per-slit table (one row per slit), and
    `flats` shows per-correction columns incl. a skipped slit (C11, S3-Q14).
    Generated by JXP and Claude.
    """
    from qtpy.QtWidgets import QTableWidget
    view, _ = _calib_view('multidet', tmp_path, qtbot)
    view._select_step('wv_calib')
    tables = view.findChildren(QTableWidget)
    assert tables and tables[-1].rowCount() == 3   # 3 slits
    # Flats: per-correction columns (Slit, Status, then mean/rms per corr).
    view._select_step('flats')
    tbl = view.findChildren(QTableWidget)[-1]
    headers = [tbl.horizontalHeaderItem(c).text()
               for c in range(tbl.columnCount())]
    assert headers[:2] == ['Slit', 'Status']
    assert any('pixelflat' in h for h in headers)
    # The third slit is skipped.
    statuses = [tbl.item(r, 1).text() for r in range(tbl.rowCount())]
    assert any('skipped' in s for s in statuses)


def test_calib_view_not_started_message(tmp_path, qtbot):
    """
    A not-started state shows a message and builds no step buttons (R11).
    Generated by JXP and Claude.
    """
    view, _ = _calib_view('not_started', tmp_path, qtbot)
    assert view._step_buttons == {}
