"""
Unit tests for the Subaru/MOIRCS spectrograph class, using synthetic
headers and files only.
"""
import numpy as np
import pytest
from astropy.io import fits
from astropy.table import Table

from pypeit import PypeItError
from pypeit import dataPaths
from pypeit.spectrographs.util import load_spectrograph

SPEC = load_spectrograph('subaru_moircs')


def _write_frame(path, det_id, exp_id):
    hdr = fits.Header()
    hdr['DET-ID'] = det_id
    hdr['EXP-ID'] = exp_id
    fits.writeto(path, np.zeros((4, 4), dtype=np.float32), hdr)
    return path


def test_companion_match(tmp_path):
    f1 = _write_frame(tmp_path / 'MCSP00237323.fits', 1, 'MCSE00237323')
    f2 = _write_frame(tmp_path / 'MCSP00237324.fits', 2, 'MCSE00237323')
    assert SPEC.companion_file(f1) == f2


def test_companion_missing(tmp_path):
    f1 = _write_frame(tmp_path / 'MCSP00237323.fits', 1, 'MCSE00237323')
    with pytest.raises(PypeItError, match='Missing the chip-2 file'):
        SPEC.companion_file(f1)


def test_companion_expid_mismatch(tmp_path):
    f1 = _write_frame(tmp_path / 'MCSP00237323.fits', 1, 'MCSE00237323')
    _write_frame(tmp_path / 'MCSP00237324.fits', 2, 'MCSE00237325')
    with pytest.raises(PypeItError, match='not the chip-2 companion'):
        SPEC.companion_file(f1)


def test_companion_not_chip1(tmp_path):
    f2 = _write_frame(tmp_path / 'MCSP00237324.fits', 2, 'MCSE00237323')
    with pytest.raises(PypeItError, match='not a MOIRCS chip-1 file'):
        SPEC.companion_file(f2)


def test_companion_match_mcsa(tmp_path):
    # VB_K raw files are named MCSA (processed primary + individual reads)
    f1 = _write_frame(tmp_path / 'MCSA00352125.fits', 1, 'MCSE00352125')
    f2 = _write_frame(tmp_path / 'MCSA00352126.fits', 2, 'MCSE00352125')
    assert SPEC.companion_file(f1) == f2
    # The MCSP file of the same exposure is not the companion
    f1p = _write_frame(tmp_path / 'MCSP00352125.fits', 1, 'MCSE00352125')
    with pytest.raises(PypeItError, match='Missing the chip-2 file'):
        SPEC.companion_file(f1p)


def _write_mcsa(path, det_id, exp_id, nsmp, primary_value):
    """
    Write a synthetic MOIRCS ``MCSA`` raw file: a 2048x2048 float32
    primary (the processed image, final minus initial reads) and
    ``2 * DET-NSMP`` int16 extensions (the individual reads).

    Generated by JXP and Claude.

    Args:
        path (`Path`_):
            File to write.
        det_id (:obj:`int`):
            ``DET-ID`` card (1 or 2).
        exp_id (:obj:`str`):
            ``EXP-ID`` card, shared by the two chips of an exposure.
        nsmp (:obj:`int`):
            ``DET-NSMP`` card (number of Fowler samples).
        primary_value (:obj:`float`):
            Constant value of the primary image.

    Returns:
        `Path`_: The path written.
    """
    hdr = fits.Header()
    hdr['DET-ID'] = det_id
    hdr['EXP-ID'] = exp_id
    hdr['DET-NSMP'] = nsmp
    hdr['EXPTIME'] = 15.
    hdr['BIN-FCT1'] = 1
    hdr['BIN-FCT2'] = 1
    primary = np.full((2048, 2048), primary_value, dtype=np.float32)
    hdus = [fits.PrimaryHDU(data=primary, header=hdr)]
    # The individual reads hold a different value, so reading one of them
    # instead of the primary would be caught
    read = np.full((2048, 2048), -7, dtype=np.int16)
    hdus += [fits.ImageHDU(data=read) for _ in range(2 * nsmp)]
    fits.HDUList(hdus).writeto(path)
    return path


def test_get_rawimage_mcsa(tmp_path):
    f1 = _write_mcsa(tmp_path / 'MCSA00352125.fits', 1, 'MCSE00352125', 1,
                     100.)
    _write_mcsa(tmp_path / 'MCSA00352126.fits', 2, 'MCSE00352125', 1, 200.)

    for det, value in [(1, 100.), (2, 200.)]:
        detpar, raw_img, hdu, exptime, datasec_img, oscansec_img \
            = SPEC.get_rawimage(f1, det)
        assert len(hdu) == 3
        # det 2 is read from the chip-2 companion
        assert hdu[0].header['DET-ID'] == det
        # The primary HDU (processed image) is read, not a read extension
        assert raw_img.shape == (2048, 2048)
        assert np.all(raw_img == value)
        assert exptime == 15.
        assert detpar['det'] == det
        # Single read: 17.5 e-, from the header of the file read
        assert np.isclose(detpar['ronoise'][0], 17.5)
        # datasec [5:2044,5:2044] (1-indexed, inclusive): 4 reference
        # pixels on each side
        assert datasec_img.sum() == 2040 * 2040
        assert np.all(datasec_img[4:2044, 4:2044] == 1)
        assert not np.any(oscansec_img)


@pytest.mark.parametrize('nsmp, ronoise', [(1, 17.5),
                                           (10, 17.5 / np.sqrt(10)),
                                           (None, 17.5 / np.sqrt(10))])
def test_ronoise_nsmp(nsmp, ronoise):
    hdr = fits.Header({'BIN-FCT1': 1, 'BIN-FCT2': 1})
    if nsmp is not None:
        hdr['DET-NSMP'] = nsmp
    hdu = fits.HDUList([fits.PrimaryHDU(header=hdr)])
    for det in [1, 2]:
        detpar = SPEC.get_detector_par(det, hdu=hdu)
        assert np.isclose(detpar['ronoise'][0], ronoise)
    # Without a file (e.g. for the bad-pixel mask), DET-NSMP = 10
    assert np.isclose(SPEC.get_detector_par(1)['ronoise'][0],
                      17.5 / np.sqrt(10))


def test_frame_typing():
    datatyp = ['DOMEFLAT', 'DOMEFLAT', 'DOMEFLAT', 'OBJECT']
    obj = ['DOMEFLAT', 'DOMEFLAT_OFF', 'MASKIMAGE', 'COSMOS2']
    hdrs = [fits.Header({'DATA-TYP': d, 'OBJECT': o})
            for d, o in zip(datatyp, obj)]
    fitstbl = Table()
    fitstbl['idname'] = [SPEC.compound_meta([h], 'idname') for h in hdrs]
    fitstbl['lampstat01'] = [SPEC.compound_meta([h], 'lampstat01')
                             for h in hdrs]
    fitstbl['exptime'] = [5., 5., 5., 180.]

    assert list(fitstbl['idname']) \
        == ['DOMEFLAT', 'DOMEFLAT_OFF', 'MASKIMAGE', 'OBJECT']
    assert list(fitstbl['lampstat01']) == ['on', 'off', 'off', 'off']
    assert np.array_equal(SPEC.check_frame_type('pixelflat', fitstbl),
                          [True, False, False, False])
    assert np.array_equal(SPEC.check_frame_type('trace', fitstbl),
                          [True, False, False, False])
    assert np.array_equal(SPEC.check_frame_type('lampoffflats', fitstbl),
                          [False, True, False, False])
    assert np.array_equal(SPEC.check_frame_type('science', fitstbl),
                          [False, False, False, True])
    assert np.array_equal(SPEC.check_frame_type('arc', fitstbl),
                          [False, False, False, True])
    # The mask image is not typed at all
    for ftype in ['pixelflat', 'lampoffflats', 'science', 'arc', 'bias',
                  'dark', 'standard']:
        assert not SPEC.check_frame_type(ftype, fitstbl)[2]


def test_frame_typing_vbk():
    # (DATA-TYP, OBJECT, EXPTIME) of the VB_K frames, plus an HK500-style
    # standard (DATA-TYP = OBJECT, short exposure)
    frames = [('DOMEFLAT', 'DOMEFLAT', 7.),            # 0 lamp-on flat
              ('DOMEFLAT', 'DOMEFLAT_OFF', 7.),        # 1 lamp-off flat
              ('DOMEFLAT', 'MASKIMAGE', 5.),           # 2 mask image
              ('INSTFLAT', 'TH-AR', 3.),               # 3 ThAr arc
              ('OBJECT', 'CC0958_PA200_1', 180.),      # 4 science
              ('STANDARD_STAR', 'HIP59174', 15.),      # 5 VB_K standard
              ('OBJECT', 'HIP59174', 15.),             # 6 HK500 standard
              ('STANDARD_STAR', 'HIP59174', 60.)]      # 7 long standard
    hdrs = [fits.Header({'DATA-TYP': d, 'OBJECT': o}) for d, o, _ in frames]
    fitstbl = Table()
    fitstbl['idname'] = [SPEC.compound_meta([h], 'idname') for h in hdrs]
    fitstbl['lampstat01'] = [SPEC.compound_meta([h], 'lampstat01')
                             for h in hdrs]
    fitstbl['exptime'] = [e for _, _, e in frames]
    assert list(fitstbl['idname']) \
        == ['DOMEFLAT', 'DOMEFLAT_OFF', 'MASKIMAGE', 'TH-AR', 'OBJECT',
            'STANDARD_STAR', 'OBJECT', 'STANDARD_STAR']

    # Use the default exposure-time ranges, as pypeit_setup does
    par = SPEC.default_pypeit_par()
    exprng = {'science': par['scienceframe']['exprng'],
              'standard': par['calibrations']['standardframe']['exprng'],
              'arc': par['calibrations']['arcframe']['exprng'],
              'tilt': par['calibrations']['tiltframe']['exprng'],
              'pixelflat': par['calibrations']['pixelflatframe']['exprng'],
              'lampoffflats':
                  par['calibrations']['lampoffflatsframe']['exprng']}

    def typed(ftype):
        return list(np.where(SPEC.check_frame_type(
            ftype, fitstbl, exprng=exprng[ftype]))[0])

    # Science and standards are split by exposure time (standard <= 20 s)
    # whether DATA-TYP is OBJECT or STANDARD_STAR
    assert typed('science') == [4, 7]
    assert typed('standard') == [5, 6]
    # Arcs and tilts are the OH lines in DATA-TYP = OBJECT frames only;
    # (as for HK500, a short OBJECT frame also passes the arc exposure-time
    # range)
    assert typed('arc') == [4, 6]
    assert typed('tilt') == [4, 6]
    assert typed('pixelflat') == [0]
    assert typed('lampoffflats') == [1]
    # The ThAr arcs and the mask image are not typed at all
    for ftype in ['pixelflat', 'trace', 'illumflat', 'lampoffflats',
                  'science', 'standard', 'arc', 'tilt', 'bias', 'dark']:
        flags = SPEC.check_frame_type(ftype, fitstbl)
        assert not flags[2] and not flags[3]


def test_dither_parsing():
    hdr_a = fits.Header({'K_DITPAT': 'LINE2', 'K_DITCNT': 1.,
                         'K_DITWID': 3.})
    hdr_b = fits.Header({'K_DITPAT': 'LINE2', 'K_DITCNT': 2.,
                         'K_DITWID': 3.})
    hdr_n = fits.Header({'K_DITPAT': 'NONE', 'K_DITCNT': 0.,
                         'K_DITWID': 0.})
    assert SPEC.compound_meta([hdr_a], 'dithpat') == 'LINE2'
    assert SPEC.compound_meta([hdr_a], 'dithpos') == 'A'
    assert SPEC.compound_meta([hdr_b], 'dithpos') == 'B'
    assert SPEC.compound_meta([hdr_a], 'dithoff') == 1.5
    assert SPEC.compound_meta([hdr_b], 'dithoff') == -1.5
    assert SPEC.compound_meta([hdr_n], 'dithpat') == 'none'
    assert SPEC.compound_meta([hdr_n], 'dithpos') == 'none'
    assert SPEC.compound_meta([hdr_n], 'dithoff') == 0.


def test_comb_group_abba():
    tbl = Table()
    tbl['frametype'] = ['arc,science,tilt'] * 4 + ['pixelflat']
    tbl['setup'] = ['A'] * 5
    tbl['dithpat'] = ['LINE2'] * 4 + ['none']
    tbl['dithpos'] = ['A', 'B', 'B', 'A', 'none']
    tbl['mjd'] = [0., 1., 2., 3., -1.]
    tbl['comb_id'] = [1, 2, 3, 4, -1]
    tbl['bkg_id'] = [-1] * 5
    tbl = SPEC.get_comb_group(tbl)
    # Each frame is paired with the closest frame at the other position
    assert list(tbl['bkg_id']) == [2, 1, 4, 3, -1]
    assert list(tbl['comb_id']) == [1, 2, 3, 4, -1]


def test_comb_group_two_standard_sets():
    # The VB_K night: a science A-B pair, then two standard sets (std1 and
    # std2, both LINE2 with different K_DITWID) ~10 min apart, plus a flat
    # and an untyped ThAr arc.  comb_id as written by pypeit_setup.
    tbl = Table()
    tbl['frametype'] = ['pixelflat,illumflat,trace', 'None']  \
        + ['arc,science,tilt'] * 2 + ['standard'] * 4
    tbl['setup'] = ['A'] * 8
    tbl['dithpat'] = ['none', 'none'] + ['LINE2'] * 6
    tbl['dithpos'] = ['none', 'none'] + ['A', 'B'] * 3
    tbl['dithoff'] = [0., 0., 1.55, -1.55, 2.4, -2.4, 2.5, -2.5]
    tbl['mjd'] = [61189.19408486, 61189.20286967,
                  61189.25360102, 61189.25605475,
                  61189.35092694, 61189.35133204,
                  61189.35845018, 61189.35904046]
    tbl['comb_id'] = [-1, -1, 1, 2, 3, 4, 5, 6]
    tbl['bkg_id'] = [-1] * 8
    tbl = SPEC.get_comb_group(tbl)
    # Science pairs with science, and each standard set within itself
    assert list(tbl['bkg_id']) == [-1, -1, 2, 1, 4, 3, 6, 5]
    assert list(tbl['comb_id']) == [-1, -1, 1, 2, 3, 4, 5, 6]


def test_sensfunc_telluric_default():
    # The IR sensfunc uses the PCA telluric model (teltype = 'pca', the
    # default); the TelFit grid needs teltype = 'grid' and could not run
    # with the previous default.
    par = SPEC.default_pypeit_par()
    assert par['sensfunc']['algorithm'] == 'IR'
    assert par['sensfunc']['IR']['teltype'] == 'pca'
    assert par['sensfunc']['IR']['telgridfile'] \
        == 'TellPCA_3000_26000_R10000.fits'


def test_config_specific_par_grisms():
    default = SPEC.default_pypeit_par()
    for dispname, arxiv in [('VB_K', 'subaru_moircs_VB_K.fits'),
                            ('HK500', 'subaru_moircs_HK500.fits')]:
        par = SPEC.config_specific_par(fits.Header({'DISPERSR': dispname}))
        wv = par['calibrations']['wavelengths']
        assert wv['method'] == 'reidentify'
        assert wv['reid_arxiv'] == arxiv
        # The archive is in the package
        assert (dataPaths.reid_arxiv.path / arxiv).is_file()

    # VB_K-specific values
    par = SPEC.config_specific_par(fits.Header({'DISPERSR': 'VB_K'}))
    wv = par['calibrations']['wavelengths']
    assert wv['lamps'] == ['OH_MOSFIRE_K']
    assert wv['fwhm'] == 6.0
    assert wv['match_toler'] == 0.75
    assert par['reduce']['findobj']['maxnumber_std'] == 1

    # HK500 keeps the instrument defaults for these
    par = SPEC.config_specific_par(fits.Header({'DISPERSR': 'HK500'}))
    wv = par['calibrations']['wavelengths']
    for key in ['lamps', 'fwhm', 'match_toler']:
        assert wv[key] == default['calibrations']['wavelengths'][key]
    assert par['reduce']['findobj']['maxnumber_std'] \
        == default['reduce']['findobj']['maxnumber_std']

    # Other grisms fall back to holy-grail
    par = SPEC.config_specific_par(fits.Header({'DISPERSR': 'zJ500'}))
    assert par['calibrations']['wavelengths']['method'] == 'holy-grail'


def test_binning():
    hdr = fits.Header({'BIN-FCT1': 2, 'BIN-FCT2': 1})
    # BIN-FCT1 is along the dispersion axis: binning is 'spec,spat'
    assert SPEC.compound_meta([hdr], 'binning') == '2,1'
    assert SPEC.compound_meta([fits.Header()], 'binning') == '1,1'


def test_valid_detector():
    assert SPEC.valid_configuration_values() == {'detector': ['1']}
    assert SPEC.ndet == 2
