
__all__ = [
    # Base class module
    'spectrograph',

    # All the subclass modules
    'aat_uhrf',
    'apf_levy',
    'bok_bc',
    'gemini_flamingos',
    'gemini_gmos',
    'gemini_gnirs',
    'gtc_osiris',
    'jwst_nircam',
    'jwst_nirspec',
    'keck_deimos',
    'keck_esi',
    'keck_hires',
    'keck_kcwi',
    'keck_lris',
    'keck_mosfire',
    'keck_nires',
    'keck_nirspec',
    'lbt_luci',
    'lbt_mods',
    'ldt_deveny',
    'magellan_fire',
    'magellan_mage',
    'mdm_modspec',
    'mdm_osmos',
    'mmt_binospec',
    'mmt_bluechannel',
    'mmt_mmirs',
    'not_alfosc',
    'ntt_efosc2',
    'p200_dbsp',
    'p200_ngps',
    'p200_tspec',
    'shane_kast',
    'soar_goodman',
    'subaru_focas',
    'tng_dolores',
    'vlt_fors',
    'vlt_sinfoni',
    'vlt_xshooter',
    'wht_isis',
]


