"""
Optional convenience entry point: ``python -m pypeit.dashboard``.

The primary launch path is the ``pypeit_dashboard`` console script
(``pypeit.scripts.pypeit_dashboard``); this module simply forwards to it so
the dashboard can also be started as a module.

Generated by JXP and Claude.
"""

from pypeit.scripts.pypeit_dashboard import RunDashboard

if __name__ == '__main__':
    RunDashboard.entry_point()
