"""
Launch PypeIt's external inspection tools as subprocesses (design C8/C14/C15).

Uses Qt's :obj:`QProcess` (S3-Q2) so launches are **non-blocking** and integrate
with the event loop: stdout/stderr/return code are captured and the
:class:`~pypeit.dashboard.view.activity.ActivityBar` is updated on start and
finish (observable launches, per the Debugging plan).

Generated by JXP and Claude.
"""

from pathlib import Path

from qtpy.QtCore import QProcess

from pypeit import log


class Launcher:
    """
    Launches external tools as non-blocking subprocesses and reports
    progress/outcome to the activity bar.

    Generated by JXP and Claude.

    Args:
        activity (:class:`~pypeit.dashboard.view.activity.ActivityBar`):
            The status/activity bar to report to (may be ``None``).
    """

    def __init__(self, activity=None):
        self.activity = activity
        # Keep references to running processes so they are not garbage
        # collected while still running.
        self._procs = []

    def _report(self, message, busy=False):
        """
        Report a message to the activity bar (and the log).

        Generated by JXP and Claude.

        Args:
            message (:obj:`str`): The message.
            busy (:obj:`bool`, optional): Show the busy indicator.

        Returns:
            None.
        """
        log.info(message)
        if self.activity is not None:
            self.activity.set_status(message, busy=busy)

    def launch(self, argv, description=None, hint='viewer window'):
        """
        Launch ``argv`` as a detached-from-the-UI subprocess.

        Generated by JXP and Claude.

        Args:
            argv (:obj:`list`): The command and its arguments.
            description (:obj:`str`, optional): Human description for the
                activity bar (defaults to the program name).
            hint (:obj:`str`, optional): Where the result appears (e.g.
                ``'Ginga window'``); shown in the finished message so the
                user knows where to look.

        Returns:
            bool: True if the process was started, False if it could not be
            launched (e.g. the target file is missing).
        """
        if not argv:
            return False
        program, args = argv[0], [str(a) for a in argv[1:]]
        label = description or program

        # If the command references a file that does not exist, report and
        # bail rather than spawning a doomed process.
        for a in args:
            if a.startswith('-'):
                continue
            if ('/' in a or a.endswith('.fits') or a.endswith('.gz')) \
                    and not Path(a).exists():
                self._report(f'Cannot launch {label}: file not found '
                             f'({a})', busy=False)
                return False

        proc = QProcess()
        proc.setProcessChannelMode(QProcess.MergedChannels)
        self._procs.append(proc)

        proc.started.connect(
            lambda: self._report(f'Launching {label}…', busy=True))
        proc.errorOccurred.connect(
            lambda _err, p=proc, lbl=label: self._on_error(p, lbl))
        proc.finished.connect(
            lambda code, _status, p=proc, lbl=label, h=hint:
            self._on_finished(p, lbl, code, h))

        proc.start(program, args)
        return True

    def _on_finished(self, proc, label, code, hint='viewer window'):
        """
        Handle process completion: report the outcome and capture output.

        Generated by JXP and Claude.

        Args:
            proc (:obj:`QProcess`): The finished process.
            label (:obj:`str`): The command label.
            code (:obj:`int`): The exit code.
            hint (:obj:`str`, optional): Where the result appears.

        Returns:
            None.
        """
        output = bytes(proc.readAll()).decode('utf-8', errors='replace')
        if code == 0:
            self._report(f'{label} finished — see the {hint}.', busy=False)
        else:
            self._report(f'{label} exited with code {code}.', busy=False)
            log.warning(f'{label} output:\n{output}')
        self._drop(proc)

    def _on_error(self, proc, label):
        """
        Handle a process that failed to start (e.g. command not found).

        Generated by JXP and Claude.

        Args:
            proc (:obj:`QProcess`): The failed process.
            label (:obj:`str`): The command label.

        Returns:
            None.
        """
        self._report(f'Failed to launch {label}: {proc.errorString()}',
                     busy=False)
        self._drop(proc)

    def _drop(self, proc):
        """
        Release a finished process reference.

        Generated by JXP and Claude.

        Args:
            proc (:obj:`QProcess`): The process to release.

        Returns:
            None.
        """
        if proc in self._procs:
            self._procs.remove(proc)
