"""
Headless (Qt-free) data/logic layer for the PypeIt Dashboard.

This module holds the dashboard's PypeIt-facing logic so it can be unit
tested with plain ``pytest`` (no display required), keeping the Qt views
thin.  Stage 0 only needs the cheap reduction metadata used by the header
banner; the full reduction-state layer (loading/deriving
``RunPypeItState``) is added in Stage 1.

Generated by JXP and Claude.
"""

from pathlib import Path
from dataclasses import dataclass

from pypeit import log

# Map the spectrograph ``pypeline`` attribute to the reduction-path label
# shown in the header.  Internally PypeIt names the IFU path 'SlicerIFU';
# the dashboard displays the shorter, user-facing 'IFU'.
PYPELINE_DISPLAY = {
    'MultiSlit': 'MultiSlit',
    'Echelle': 'Echelle',
    'SlicerIFU': 'IFU',
}


@dataclass
class HeaderInfo:
    """
    Cheap, no-reduction metadata describing a reduction, used to populate
    the dashboard's shared header banner (design requirement R6).

    Generated by JXP and Claude.

    Attributes:
        pypeit_file (str):
            Name of the ``.pypeit`` file (basename, for display).
        spectrograph (str):
            The spectrograph name (``PYP_SPEC``), e.g. ``shane_kast_blue``.
        setup (str):
            The setup/configuration identifier, e.g. ``A``.  May be ``None``
            if the ``.pypeit`` file does not define one.
        path (str):
            The reduction path label: ``MultiSlit``, ``Echelle``, or ``IFU``.
        redux_dir (str):
            The reduction directory (absolute path).
    """
    pypeit_file: str
    spectrograph: str
    setup: str
    path: str
    redux_dir: str


def read_header_info(pypeit_file, redux_path=None):
    """
    Parse a ``.pypeit`` file and return the cheap metadata needed by the
    header banner, performing no reduction.

    Generated by JXP and Claude.

    Args:
        pypeit_file (:obj:`str`, `pathlib.Path`_):
            Path to the ``.pypeit`` reduction file.
        redux_path (:obj:`str`, optional):
            Reduction directory.  If ``None``, the directory containing
            ``pypeit_file`` is used.

    Returns:
        :class:`HeaderInfo`: The parsed header metadata.

    Raises:
        FileNotFoundError:
            If ``pypeit_file`` does not exist (R11 edge case: the named
            ``.pypeit`` file is absent).
    """
    # Import here to avoid importing the heavy pypeit machinery at module
    # load time (keeps GUI startup snappy and module imports cheap).
    from pypeit.inputfiles import PypeItFile

    path = Path(pypeit_file)
    if not path.is_file():
        # R11: surface a clear, typed error rather than crashing later.
        raise FileNotFoundError(f'PypeIt file not found: {path}')

    # vet=False: we only need the configuration metadata for the header, not
    # a full validation of the data block (that is run_pypeit's job).
    pyfile = PypeItFile.from_file(str(path), vet=False)
    spec = pyfile.get_spectrograph()

    # Map the internal pypeline name to the user-facing path label.
    path_label = PYPELINE_DISPLAY.get(spec.pypeline, spec.pypeline)

    redux_dir = Path(redux_path) if redux_path is not None else path.parent

    return HeaderInfo(pypeit_file=path.name,
                      spectrograph=spec.name,
                      setup=pyfile.setup_name,
                      path=path_label,
                      redux_dir=str(redux_dir.resolve()))
