"""
The main window for the PypeIt Dashboard.

The window mirrors the ``setup_gui`` ``QMainWindow``-based layout: a shared
header banner (R6) at the top and a tab bar with the **Status** and
**Calibrations** tabs below.  In Stage 0 the two tabs hold placeholder
widgets.

Generated by JXP and Claude.
"""

from qtpy.QtWidgets import (QMainWindow, QWidget, QVBoxLayout, QTabWidget)

from pypeit.dashboard.view.header import HeaderBanner
from pypeit.dashboard.view.status_view import StatusView
from pypeit.dashboard.view.calibrations_view import CalibrationsView

# Tab labels, in display order.  Kept as a constant so tests can assert the
# exact tab bar (Status | Calibrations).
TAB_LABELS = ('Status', 'Calibrations')

# The design's default window size (matches setup_gui and the layout
# sketches).
DEFAULT_SIZE = (1650, 900)


class DashboardMainWindow(QMainWindow):
    """
    The PypeIt Dashboard main window (Stage 0 walking skeleton).

    Generated by JXP and Claude.

    Args:
        header_info (:class:`pypeit.dashboard.model.HeaderInfo`):
            Reduction metadata used to populate the header banner (R6).
        parent (:obj:`QWidget`, optional):
            The parent widget (normally ``None`` for a top-level window).
    """

    def __init__(self, header_info, parent=None):
        super().__init__(parent=parent)

        self.header_info = header_info

        # Central widget: header banner stacked above the tab bar.
        central = QWidget(self)
        layout = QVBoxLayout(central)

        self.header = HeaderBanner(header_info, parent=central)
        layout.addWidget(self.header)

        # The two-tab bar (Status | Calibrations).  Views are placeholders
        # in Stage 0; they are populated in Stages 2 and 3.
        self.tab_widget = QTabWidget(parent=central)
        self.status_view = StatusView(parent=self.tab_widget)
        self.calibrations_view = CalibrationsView(parent=self.tab_widget)
        self.tab_widget.addTab(self.status_view, TAB_LABELS[0])
        self.tab_widget.addTab(self.calibrations_view, TAB_LABELS[1])
        layout.addWidget(self.tab_widget, stretch=1)

        self.setCentralWidget(central)

        self.setWindowTitle('PypeIt Dashboard')
        self.resize(*DEFAULT_SIZE)
