name: Cron tests on develop branch

on:
  schedule:
    # run every Monday at 8am UTC
    - cron: '0 8 * * 1'

env:
  SETUP_XVFB: True  # avoid issues if something tries to open a GUI window

jobs:
  cron-tests:
    name: Tox env ${{ matrix.python }}-${{ matrix.toxenv }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8, 3.9]
        toxenv: [test-alldeps, test-numpydev, test-linetoolsdev, test-gingadev, test-astropydev, conda]
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        ref: develop
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install base dependencies
      run: |
        python -m pip install --upgrade pip tox
    - name: Test with tox
      run: |
        tox -e ${{ matrix.toxenv }}
